[env]
CARGO_TARGET_DIR = "target"
PROFILE = "release"
PROFILE_DIR = "release"
INCLUDE_DIR = "include"
CC_DIR = "${CARGO_TARGET_DIR}/${PROFILE_DIR}/libafl_cc"
CXX_DIR = "${CARGO_TARGET_DIR}/${PROFILE_DIR}/libafl_cxx"
COVERAGE_DIR = "./${CARGO_TARGET_DIR}/${INCLUDE_DIR}/coverage.o"
ZEPHYR_PROJECT_DIR = "../../zephyrproject/zephyr"
ZEPHYR_EXE_DIR = "./${CARGO_TARGET_DIR}/target"
FUZZER_DIR = "./${CARGO_TARGET_DIR}/${PROFILE_DIR}/fuzzer"


[tasks.build_zephyr]
script_runner = "@shell"
script = '''
export CUSTOM_TARGET_DIR="$(realpath ${ZEPHYR_EXE_DIR})"

cd ${ZEPHYR_PROJECT_DIR}

. ../.venv/bin/activate

export ZEPHYR_TOOLCHAIN_VARIANT="llvm"

west build \
    -b native_sim \
    samples/net/sockets/echo \
    -d "$CUSTOM_TARGET_DIR" \
    ${ZEPHYR_PRISTINE:+--pristine} \
    -- \
    -DEXTRA_CFLAGS="-g -O2 -fsanitize-coverage=trace-pc-guard"
'''

[tasks.build_fuzzer]
script_runner = "@shell"
script = '''
cargo build --profile release
'''

[tasks.run]
dependencies = ["build_fuzzer", "build_zephyr"]
script_runner = "@shell"
script = '''
${FUZZER_DIR} --zephyr-exec-dir ${ZEPHYR_EXE_DIR}/zephyr/zephyr.exe --stdout stdout.log --stderr stderr.log --monitor-path monitor.toml ${@}
'''

[tasks.run_fast]
dependencies = ["build_fuzzer"]
script_runner = "@shell"
script = '''
echo "\n\n\e[33mWarning: Not recompiling Zephyr. Use target run to do so.\e[0m\n\n\n\n"
sleep 1
${FUZZER_DIR} --zephyr-exec-dir ${ZEPHYR_EXE_DIR}/zephyr/zephyr.exe --stdout stdout.log --stderr stderr.log --monitor-path monitor.toml ${@}
'''

[tasks.zephyr_diff]
script_runner = "@shell"
script = '''
FUZZER_DIR="$(realpath ../zephyr.diff)"
cd ${ZEPHYR_PROJECT_DIR}
git diff > "${FUZZER_DIR}"
'''
